"""add lesson metadata fields for ethaksalawa

Revision ID: 70deebbd96d5
Revises: d5d1e0c26233
Create Date: 2026-07-20 15:17:45.937011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70deebbd96d5'
down_revision = 'd5d1e0c26233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('resource_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('download_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_provider', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('resource_links', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lessons_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_unit_number'), ['unit_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_unit_number'))
        batch_op.drop_index(batch_op.f('ix_lessons_language'))
        batch_op.drop_index(batch_op.f('ix_lessons_grade'))
        batch_op.drop_column('resource_links')
        batch_op.drop_column('source_provider')
        batch_op.drop_column('source_url')
        batch_op.drop_column('download_url')
        batch_op.drop_column('resource_url')
        batch_op.drop_column('image_url')
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('language')
        batch_op.drop_column('unit_number')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
